/* =========================================================================
   datos.js  -  contenido de consulta (lo usan la presentación y la guía)
   Podés agregar o corregir entradas: cada línea es un elemento entre { }.
   Cuidá las comas al final de cada línea (todas menos la última de cada lista).
     ev    -> cronología:  k = orden, d = fecha visible, p = país, t = texto, v = true si está sin verificar
     glos  -> glosario:    t = término, d = definición
     verbos-> palabras:    grupos con w = palabra y m = qué implica
     qa    -> preguntas:   q = pregunta, a = respuesta
   ========================================================================= */
window.DATOS = {
  /* Cronología */
  ev: [
    {"k":"1908","d":"1908","p":"Uruguay","t":"Congreso de Estudiantes Americanos en Montevideo: antecedente de la coordinación estudiantil continental.","v":true},
    {"k":"1917-12","d":"fines de 1917","p":"Argentina","t":"Los estudiantes de Medicina de Córdoba protestan por la eliminación del internado del Hospital de Clínicas.","v":false},
    {"k":"1918-03","d":"marzo 1918","p":"Argentina","t":"Se organiza el Comité Pro-Reforma, se declara la huelga general y se difunde el Manifiesto a la juventud argentina. Las autoridades cierran la universidad.","v":false},
    {"k":"1918-04","d":"abril 1918","p":"Argentina","t":"Se funda la Federación Universitaria Argentina (FUA).","v":false},
    {"k":"1918-04-11","d":"11 abr 1918","p":"Argentina","t":"El gobierno de Yrigoyen decreta la intervención de la Universidad de Córdoba.","v":false},
    {"k":"1918-06-15","d":"15 jun 1918","p":"Argentina","t":"Fecha simbólica de la Reforma: la Asamblea elige rector a Antonio Nores (candidato de la Corda Frates) y los estudiantes irrumpen para impedirlo. Segunda huelga general.","v":false},
    {"k":"1918-06-21","d":"21 jun 1918","p":"Argentina","t":"Manifiesto Liminar de la Federación Universitaria de Córdoba: «La juventud argentina de Córdoba a los hombres libres de Sud América». Su redacción se atribuye a Deodoro Roca.","v":false},
    {"k":"1918-09-09","d":"9 sep 1918","p":"Argentina","t":"La Federación Universitaria de Córdoba asume la dirección de la universidad; el gobierno ordena al Ejército reprimir la ocupación.","v":false},
    {"k":"1918-10","d":"oct 1918","p":"Argentina","t":"Se cierra la etapa más intensa del conflicto (marzo–octubre). Yrigoyen intervino dos veces la universidad para que se reformaran los estatutos y hubiera nuevas elecciones.","v":false},
    {"k":"1919","d":"1919","p":"Perú","t":"El movimiento reformista llega a Perú (Lima).","v":false},
    {"k":"1921-09","d":"sep–oct 1921","p":"México","t":"Primer Congreso Internacional de Estudiantes en la Ciudad de México.","v":false},
    {"k":"1922","d":"1922–1923","p":"Cuba","t":"Se funda la Federación Estudiantil Universitaria (FEU, 1922) y se proclama la Reforma Universitaria de 1923, con Julio Antonio Mella como referente.","v":false},
    {"k":"1928-02","d":"6–12 feb 1928","p":"Venezuela","t":"«Semana del Estudiante» en Caracas: la Generación del 28 termina enfrentada al régimen de Juan Vicente Gómez; cientos de jóvenes son encarcelados.","v":false},
    {"k":"1929-06-07","d":"7 jun 1929","p":"Colombia","t":"Es asesinado el estudiante Gonzalo Bravo Pérez. Su entierro (8 de junio) da origen al Día del Estudiante Caído.","v":false},
    {"k":"1954-06-08","d":"8–9 jun 1954","p":"Colombia","t":"Es asesinado Uriel Gutiérrez (8/6). Al día siguiente una marcha estudiantil es baleada en Bogotá (la cifra de víctimas se discute; al menos ocho).","v":false},
    {"k":"1966-06-28","d":"28 jun 1966","p":"Argentina","t":"Golpe de Estado que derroca a Arturo Illia; asume Juan Carlos Onganía.","v":false},
    {"k":"1966-07-29","d":"29 jul 1966","p":"Argentina","t":"Decreto-ley 16.912: fin de la autonomía y del cogobierno. «Noche de los Bastones Largos»: la Policía desaloja facultades de la UBA (Exactas, en Perú 222) y unos 1.300 docentes renuncian.","v":false},
    {"k":"1967","d":"1967","p":"Chile","t":"Toma de la Casa Central de la Universidad Católica en reclamo de una reforma universitaria.","v":true},
    {"k":"1968-03-28","d":"28 mar 1968","p":"Brasil","t":"Muere Edson Luís de Lima Souto (18 años) durante una protesta por el restaurante estudiantil Calabouço, en Río de Janeiro.","v":false},
    {"k":"1968-06-26","d":"26 jun 1968","p":"Brasil","t":"Passeata dos Cem Mil en Río: más de cien mil personas.","v":false},
    {"k":"1968-07-22","d":"22 jul 1968","p":"México","t":"Riña entre estudiantes de la preparatoria Isaac Ochoterena y de las vocacionales 2 y 5 del IPN. Los granaderos entran a los planteles: comienza el conflicto.","v":false},
    {"k":"1968-08-02","d":"2 ago 1968","p":"México","t":"Se funda el Consejo Nacional de Huelga (CNH).","v":false},
    {"k":"1968-08-04","d":"4 ago 1968","p":"México","t":"El CNH da a conocer su pliego petitorio de seis puntos.","v":false},
    {"k":"1968-08-13","d":"13 ago 1968","p":"México","t":"Manifestación multitudinaria (más de 100 mil personas).","v":false},
    {"k":"1968-08-14","d":"14 ago 1968","p":"Uruguay","t":"Muere Líber Arce, baleado dos días antes en una marcha por el boleto estudiantil: primer estudiante asesinado. Hoy es el Día de los Mártires Estudiantiles.","v":false},
    {"k":"1968-08-27","d":"27 ago 1968","p":"México","t":"Marcha de más de 500 mil personas hacia el Zócalo.","v":false},
    {"k":"1968-09-13","d":"13 sep 1968","p":"México","t":"Marcha del Silencio.","v":false},
    {"k":"1968-09-18","d":"18 sep 1968","p":"México","t":"El Ejército ocupa Ciudad Universitaria.","v":false},
    {"k":"1968-09-20","d":"20–21 sep 1968","p":"Uruguay","t":"Son baleados frente a la Universidad Hugo de los Santos (19) y Susana Pintos; ambos mueren.","v":false},
    {"k":"1968-10-02","d":"2 oct 1968","p":"México","t":"Matanza de Tlatelolco, en la Plaza de las Tres Culturas. Las cifras de víctimas siguen en discusión: entre unas 25 y más de 300 según las fuentes.","v":false},
    {"k":"1968-10-12","d":"12 oct 1968","p":"México","t":"Se inauguran los Juegos Olímpicos en la Ciudad de México.","v":false},
    {"k":"1968-12-13","d":"13 dic 1968","p":"Brasil","t":"Acto Institucional n.º 5 (AI-5): endurece la dictadura.","v":false},
    {"k":"1969-05-15","d":"15 may 1969","p":"Argentina","t":"Corrientes: muere el estudiante Juan José Cabral en una protesta por el aumento del precio del comedor universitario (Correntinazo).","v":false},
    {"k":"1969-05-17","d":"17 may 1969","p":"Argentina","t":"Rosario: muere el estudiante Adolfo Bello (Rosariazo). El 21/5, durante una marcha del silencio, muere Luis Blanco, de 15 años.","v":false},
    {"k":"1969-05-29","d":"29 may 1969","p":"Argentina","t":"Cordobazo: gran movilización conjunta de obreros y estudiantes en Córdoba.","v":false},
    {"k":"1971-06-10","d":"10 jun 1971","p":"México","t":"«Halconazo» o Matanza del Jueves de Corpus: un grupo paramilitar ataca una marcha estudiantil; decenas de muertos.","v":false},
    {"k":"1975-07-30","d":"30 jul 1975","p":"El Salvador","t":"Masacre estudiantil: el Ejército reprime una marcha de la Universidad de El Salvador (número de víctimas indeterminado).","v":false},
    {"k":"1975","d":"1975","p":"Argentina","t":"Estudiantes secundarios de La Plata reclaman el boleto estudiantil.","v":false},
    {"k":"1976-09-16","d":"16 sep 1976","p":"Argentina","t":"Noche de los Lápices: entre el 8 y el 21 de septiembre son secuestrados diez estudiantes secundarios de La Plata; seis siguen desaparecidos y cuatro sobrevivieron.","v":false},
    {"k":"1985","d":"1985","p":"Argentina","t":"Juicio a las Juntas: el testimonio de Pablo Díaz da notoriedad pública a la Noche de los Lápices.","v":false},
    {"k":"1986","d":"1986","p":"Argentina","t":"Se estrena la película «La noche de los lápices».","v":false},
    {"k":"1998-05-14","d":"14 may 1998","p":"Argentina","t":"La Legislatura de la Ciudad de Buenos Aires fija el 16 de septiembre como Día de los Derechos del Estudiante Secundario.","v":false},
    {"k":"2006","d":"2006 (pico en mayo)","p":"Chile","t":"Revolución Pingüina: tomas y paros de estudiantes secundarios contra la LOCE, por la gratuidad de la PSU y el pase escolar. Paro nacional del 30 de mayo. Las fuentes ubican el inicio en abril y algunas extienden la movilización hasta fin de año.","v":false},
    {"k":"2009-08","d":"ago 2009","p":"Chile","t":"Se promulga la Ley General de Educación (LGE), que deroga la LOCE.","v":false},
    {"k":"2011-03-10","d":"10 mar 2011","p":"Colombia","t":"El gobierno de Santos presenta su proyecto de reforma de la Ley 30 de educación superior.","v":false},
    {"k":"2011-04-28","d":"28 abr 2011","p":"Chile","t":"Primera marcha nacional del movimiento de 2011, convocada por la Confech. Vocera destacada: Camila Vallejo (FECH).","v":false},
    {"k":"2011-06-13","d":"13 jun–27 ago 2011","p":"Chile","t":"«1.800 horas por la educación»: estudiantes corren alrededor de La Moneda. En junio también hay una marcha de los 100 mil (16/6) y el flashmob «Thriller».","v":false},
    {"k":"2011-08-24","d":"24–25 ago 2011","p":"Chile","t":"Paro nacional de dos días convocado por la CUT, junto al movimiento estudiantil.","v":false},
    {"k":"2011-10-12","d":"12 oct 2011","p":"Colombia","t":"La MANE declara el paro nacional universitario indefinido. El 26/10 hay «abrazos» a las universidades.","v":false},
    {"k":"2011-11-09","d":"9–16 nov 2011","p":"Colombia","t":"El gobierno anuncia el retiro del proyecto (9/11); marcha nacional junto a Fecode (10/11); la Comisión Sexta de la Cámara lo retira formalmente (16/11).","v":false},
    {"k":"2013-06","d":"jun 2013","p":"Brasil","t":"Movimiento Passe Livre: las protestas contra el aumento del pasaje en São Paulo se vuelven masivas.","v":true},
    {"k":"2013-07-03","d":"3 jul 2013","p":"Argentina","t":"Se sanciona la Ley 26.877 de Creación y Funcionamiento de los Centros de Estudiantes (promulgada el 1/8; publicada en el B.O. el 6/8).","v":false},
    {"k":"2014-09-26","d":"26 sep 2014","p":"México","t":"Ayotzinapa: desaparecen 43 estudiantes de la Escuela Normal Rural «Raúl Isidro Burgos», en Iguala (Guerrero).","v":false},
    {"k":"2015-06-03","d":"3 jun 2015","p":"Argentina","t":"Primera marcha «Ni Una Menos».","v":false},
    {"k":"2015-11-09","d":"9 nov–4 dic 2015","p":"Brasil","t":"Ocupaciones de escuelas en São Paulo (unas 200) contra la «reorganización escolar». El gobierno la suspende el 4 de diciembre.","v":false},
    {"k":"2016-10","d":"oct 2016","p":"Brasil","t":"Ocupaciones de escuelas y universidades en varios estados (más de 800 en Paraná según algunas fuentes) contra la MP 746 (reforma del Ensino Médio) y la PEC 241.","v":false},
    {"k":"2018-04-17","d":"17 abr–25 may 2018","p":"Chile","t":"Mayo feminista: primera toma en la Universidad Austral (17/4), Derecho de la U. de Chile (27/4), marcha del 16/5 y toma de la Casa Central de la UC (25/5).","v":false},
    {"k":"2019-10-06","d":"6–18 oct 2019","p":"Chile","t":"Alza del Metro (6/10), evasiones masivas de estudiantes secundarios y estallido social del 18/10.","v":false},
    {"k":"2024-04-23","d":"23 abr 2024","p":"Argentina","t":"Primera Marcha Federal Universitaria en defensa de la universidad pública.","v":false},
    {"k":"2024-10-02","d":"2 oct 2024","p":"Argentina","t":"Segunda Marcha Federal Universitaria.","v":false},
    {"k":"2025-09-17","d":"17 sep 2025","p":"Argentina","t":"Tercera Marcha Federal Universitaria.","v":false}
  ],
  /* Glosario */
  glos: [
    {"t":"Autonomía universitaria","d":"Derecho de la universidad a gobernarse por sus propios órganos, sin depender del gobierno de turno. Principio de la Reforma de 1918; suprimido en Argentina por el decreto-ley 16.912 (1966)."},
    {"t":"Cogobierno","d":"Gobierno de la universidad compartido por profesores, graduados y estudiantes. No es lo mismo que autonomía: la autonomía es hacia afuera (frente al Estado), el cogobierno es hacia adentro (quién decide)."},
    {"t":"Docencia libre","d":"Posibilidad de enseñar sin depender de un único programa oficial; se suele asociar con libertad de cátedra."},
    {"t":"Asistencia libre","d":"Principio reformista por el que el estudiante no está obligado a asistir a todas las clases para poder rendir."},
    {"t":"Extensión universitaria","d":"Función de la universidad de llevar su conocimiento y sus servicios a la sociedad, más allá de las aulas."},
    {"t":"Cátedra vitalicia","d":"Cargo docente sin límite de tiempo. La Reforma pidió concursos y periodicidad de cátedras."},
    {"t":"Corda Frates","d":"Asociación católica conservadora cuyo candidato, Antonio Nores, fue elegido rector el 15 de junio de 1918."},
    {"t":"Clericalismo","d":"Influencia de la Iglesia (y de sectores católicos conservadores) sobre instituciones como la universidad."},
    {"t":"Manifiesto Liminar","d":"Documento del 21 de junio de 1918 de la Federación Universitaria de Córdoba. «Liminar» significa «de umbral, de comienzo»."},
    {"t":"Intervención","d":"Decisión del gobierno de desplazar a las autoridades de una institución y designar a un interventor."},
    {"t":"Toma / ocupación","d":"Forma de protesta en la que los estudiantes ocupan un edificio educativo. Es un recurso extremo que suele aparecer cuando se sienten no escuchados."},
    {"t":"Paro / huelga","d":"Suspensión de actividades como medida de protesta."},
    {"t":"Pliego petitorio","d":"Lista escrita y ordenada de demandas. Ejemplo: los seis puntos del CNH mexicano (4 de agosto de 1968)."},
    {"t":"Consigna","d":"Frase corta y repetible que resume un reclamo: «2 de octubre no se olvida»."},
    {"t":"Marcha del silencio","d":"Marcha sin consignas ni cantos, en homenaje o en repudio de un hecho de violencia (México, 13/9/1968; Rosario, 21/5/1969)."},
    {"t":"Boleto estudiantil","d":"Tarifa reducida o gratuita de transporte para estudiantes. Reclamo presente en Uruguay 1968, La Plata 1975, Chile 2006, Brasil 2013."},
    {"t":"Centro de estudiantes","d":"Organización de representación estudiantil de cada establecimiento. En Argentina, la Ley 26.877 (2013) obliga a reconocerlos como «órganos democráticos de representación estudiantil»."},
    {"t":"Federación estudiantil","d":"Organización que agrupa a los estudiantes de varias instituciones: FUA (Argentina), FECH (Universidad de Chile), FEU (Cuba), FEUU (Uruguay), UNE (Brasil)."},
    {"t":"Secundarista / pingüino","d":"Estudiante secundario. «Pingüinos» se llamó a los secundarios chilenos de 2006 por su uniforme blanco y negro."},
    {"t":"Normal rural","d":"Escuela que forma maestros rurales, en México, para jóvenes de sectores humildes. Ayotzinapa es una de ellas."},
    {"t":"Confech","d":"Confederación de Estudiantes de Chile, que convocó la primera marcha nacional de 2011."},
    {"t":"MANE","d":"Mesa Amplia Nacional Estudiantil (Colombia, 2011)."},
    {"t":"CNH","d":"Consejo Nacional de Huelga (México, 1968): órgano de dirección del movimiento, con tres representantes por escuela en huelga."},
    {"t":"Granaderos","d":"Cuerpo policial antidisturbios de la Ciudad de México en 1968."},
    {"t":"Halcones","d":"Grupo paramilitar que atacó la marcha estudiantil del 10 de junio de 1971."},
    {"t":"Dictadura cívico-militar","d":"Régimen de facto sostenido por las Fuerzas Armadas con apoyo de sectores civiles (Argentina, 1976–1983)."},
    {"t":"Terrorismo de Estado","d":"Uso sistemático del aparato estatal para secuestrar, torturar y hacer desaparecer personas fuera de todo marco legal."},
    {"t":"Desaparición forzada","d":"Secuestro de una persona por agentes del Estado o con su aval, seguido de la negativa a informar su destino."},
    {"t":"Lesa humanidad","d":"Crímenes graves cometidos de forma sistemática contra la población civil. La CNDH mexicana usa este término para Tlatelolco."},
    {"t":"Masacre / matanza","d":"Ataque armado contra personas indefensas. Es una palabra con valoración fuerte: úsenla cuando las fuentes o la justicia la usan."},
    {"t":"Memoria, Verdad y Justicia","d":"Consigna de los organismos de derechos humanos en Argentina."},
    {"t":"Ánimo de lucro","d":"Que persigue una ganancia económica. En Colombia 2011 fue el punto central del rechazo a la reforma de la Ley 30."},
    {"t":"Gratuidad","d":"Que no se cobra arancel a los estudiantes. Reclamo central de Chile 2011."},
    {"t":"Alianza obrero-estudiantil","d":"Acción conjunta de trabajadores y estudiantes. Ejemplo clave: el Cordobazo (29/5/1969)."},
    {"t":"Estallido social","d":"Movilización masiva y espontánea que desborda su reclamo inicial. Chile, 18 de octubre de 2019."},
    {"t":"Mayo feminista","d":"Ola de tomas y marchas de estudiantes en Chile, en 2018, contra el acoso y por una educación no sexista."},
    {"t":"Educación no sexista","d":"Reclamo de que la enseñanza y las instituciones no reproduzcan desigualdades de género."},
    {"t":"Primavera Secundarista","d":"Ola de ocupaciones de escuelas por parte de estudiantes secundarios de Brasil en 2015–2016."}
  ],
  /* Palabras que cambian el enfoque */
  verbos: [
    {"t":"Lo que hicieron los estudiantes","i":[{"w":"pidieron","m":"Suena a solicitar algo a alguien que decide. Es débil. El Manifiesto de 1918 lo usa justo para rechazarlo: «La juventud ya no pide. Exige»."},{"w":"reclamaron","m":"Reclamar es hablar de un derecho que se considera propio. Es la palabra más segura y más usada en historia social."},{"w":"exigieron","m":"Más firme que «reclamaron»: no admite negociar el punto. Usenla solo si el documento o el contexto lo respaldan."},{"w":"demandaron / plantearon","m":"Neutras y formales. Sirven cuando quieren describir sin valorar."},{"w":"denunciaron","m":"Hacer público un abuso o una injusticia (acoso en 2018, represión en 1968)."},{"w":"cuestionaron","m":"Pusieron en duda un orden establecido (autoridades, planes de estudio, el sistema educativo)."},{"w":"se organizaron / se movilizaron","m":"Describen el proceso colectivo, sin decir todavía si funcionó."},{"w":"ocuparon / tomaron","m":"«Ocupar» es más neutro; «tomar» es la palabra de los propios estudiantes. Nunca «invadieron», que suena a ilegitimidad."}]},
    {"t":"Lo que consiguieron (o no)","i":[{"w":"hizo","m":"Palabra plana: dice que algo ocurrió, pero no si fue un éxito. Casi siempre se puede reemplazar por otra más precisa."},{"w":"logró / consiguió","m":"Implica un resultado favorable respecto de lo que se buscaba. Usenla solo si el resultado está comprobado (ej.: Colombia 2011 logró que se retirara el proyecto)."},{"w":"obtuvo","m":"El resultado se recibió (una concesión, una ley). Pone el foco en lo que se recibe, no en el esfuerzo."},{"w":"impulsó / promovió","m":"Empujó un proceso, sin garantizar que llegó a buen puerto. Ideal para «impulsó el debate sobre la gratuidad»."},{"w":"contribuyó a","m":"Cuando fue una causa entre varias. Evita exagerar el papel estudiantil."},{"w":"no logró / quedó a medias","m":"Resultado parcial. Ej.: los pingüinos de 2006 lograron abrir el debate, pero quedaron afuera del acuerdo de 2007 que derogó la LOCE."},{"w":"victoria / conquista","m":"«Conquista» es una palabra de los movimientos sociales; en un trabajo escolar conviene justificarla («conquista» = derecho obtenido tras una lucha)."}]},
    {"t":"Lo que hizo el Estado o el poder","i":[{"w":"reprimió","m":"Uso de la fuerza para frenar una protesta. Es la palabra más clara y precisa para Tlatelolco, Bastones Largos o el Halconazo."},{"w":"intervino","m":"Puede ser un término legal (intervención de una universidad) o un eufemismo. Aclaren de cuál hablan."},{"w":"desalojó","m":"Sacar por la fuerza a quienes ocupan un lugar. Describe el acto, no lo valora."},{"w":"secuestró / desapareció","m":"Términos exactos para la Noche de los Lápices. No es lo mismo que «detuvo» (detención legal) ni que «murieron»."},{"w":"masacre / matanza","m":"Valoración fuerte. Respáldenla con la fuente (la CNDH mexicana la usa para Tlatelolco)."},{"w":"dictadura / gobierno de facto","m":"«De facto» describe cómo llegó al poder (sin elecciones); «dictadura» valora cómo gobierna. En Argentina se usa «dictadura cívico-militar»."}]},
    {"t":"Cómo llamar al fenómeno","i":[{"w":"protesta / movilización","m":"Términos amplios. «Protesta» es puntual; «movilización» sugiere organización y duración."},{"w":"movimiento","m":"Implica organización, programa y continuidad en el tiempo. No todo estallido es un movimiento."},{"w":"revuelta / rebelión","m":"Suben la intensidad y el conflicto; el Manifiesto de 1918 dice «rebeldía»."},{"w":"causa / detonante / consecuencia","m":"Tres cosas distintas: la causa es de fondo (desigualdad), el detonante es la chispa (el pasaje, el comedor) y la consecuencia es lo que vino después."},{"w":"estudiantes / jóvenes / secundarios","m":"No son sinónimos. Cuando hablen del boleto, de la Noche de los Lápices o de Chile 2006, precisen «secundarios»."}]}
  ],
  /* Preguntas del profe */
  qa: [
    {"q":"¿Qué fue la Reforma Universitaria de 1918 y por qué importa?","a":"Fue una rebelión estudiantil en la Universidad de Córdoba (marzo–octubre de 1918) que reclamó democratizar la universidad: cogobierno, autonomía, docencia libre y extensión. Su fecha simbólica es el 15 de junio. Importa porque se convirtió en modelo para los movimientos estudiantiles de todo el continente."},
    {"q":"¿Cuál es la diferencia entre autonomía y cogobierno?","a":"Autonomía: la universidad se gobierna sin depender del gobierno de turno (hacia afuera). Cogobierno: dentro de la universidad deciden juntos profesores, graduados y estudiantes (hacia adentro). El decreto-ley 16.912 de 1966 eliminó ambos."},
    {"q":"¿Por qué se dice que la Reforma fue latinoamericana y no solo argentina?","a":"Porque el Manifiesto Liminar se dirige «a los hombres libres de Sud América» y porque sus ideas se difundieron: Perú (1919), el Congreso Internacional de Estudiantes en México (1921) y Cuba (1923), entre otros."},
    {"q":"¿Qué dice el Manifiesto Liminar?","a":"Critica a la universidad como refugio de una minoría y de «una secta religiosa»; reclama un gobierno «estrictamente democrático» en el que los estudiantes tengan voz; y se declara parte de «una hora americana». Fue firmado el 21 de junio de 1918 por dirigentes de la FUC; se atribuye su redacción a Deodoro Roca."},
    {"q":"¿Cuál es la tesis del grupo?","a":"Que los movimientos estudiantiles latinoamericanos casi siempre empiezan por lo cotidiano (el boleto, el comedor, el techo de la escuela) y terminan discutiendo quién tiene derecho a estudiar, a participar y a ser escuchado. (Ajusten esta frase a lo que realmente piensan.)"},
    {"q":"¿Por qué eligieron el enfoque social y no el político?","a":"Porque acá miramos a las personas: qué necesitaban, cómo se organizaron, qué costo pagaron y cómo se recuerdan. Lo político y lo económico están en el trasfondo, pero no los analizamos: por eso decimos que los «minimizamos», no que no existan."},
    {"q":"¿Qué pasó el 2 de octubre de 1968?","a":"En Tlatelolco, Ciudad de México, durante un mitin en la Plaza de las Tres Culturas (unas 10 mil personas según la CNDH), el Ejército y fuerzas de seguridad dispararon contra los presentes. Las cifras de víctimas siguen en discusión (entre unas 25 y más de 300 según las fuentes). La CNDH lo califica como matanza y crimen de lesa humanidad."},
    {"q":"¿Qué pidió el CNH mexicano?","a":"Seis puntos (4/8/1968): libertad de presos políticos; destitución de los jefes policiales Cueto y Mendiolea (y del coronel Frías); extinción del cuerpo de granaderos; derogación de los artículos 145 y 145 bis (delito de «disolución social»); indemnización a las víctimas; y deslinde de responsabilidades."},
    {"q":"¿Qué fue la Noche de los Lápices y por qué se llama así?","a":"Fue el secuestro, entre el 8 y el 21 de septiembre de 1976 (con epicentro el 16), de diez estudiantes secundarios de La Plata que habían reclamado el boleto estudiantil. Seis siguen desaparecidos. El nombre se popularizó desde el testimonio de Pablo Díaz en el Juicio a las Juntas (1985) y la película de 1986, por tratarse de jóvenes estudiantes."},
    {"q":"¿Por qué se recuerda el 16 de septiembre?","a":"Es el Día de los Derechos del Estudiante Secundario: lo fijó la Legislatura porteña el 14 de mayo de 1998 y se recuerda en todo el país. En 2026 se cumplieron 50 años del hecho."},
    {"q":"¿Qué es la Ley 26.877?","a":"La ley de Creación y Funcionamiento de los Centros de Estudiantes (sancionada el 3/7/2013, promulgada el 1/8/2013). Obliga a reconocerlos como «órganos democráticos de representación estudiantil» en escuelas secundarias, institutos superiores y modalidad de adultos."},
    {"q":"¿Qué diferencia hay entre los Bastones Largos (1966) y el Cordobazo (1969)?","a":"Bastones Largos: la Policía desalojó facultades de la UBA tras el decreto-ley 16.912 (29/7/1966), con unos 1.300 renuncias docentes. Cordobazo: el 29/5/1969 obreros y estudiantes se movilizaron juntos en Córdoba, después de las muertes de los estudiantes Cabral y Bello."},
    {"q":"¿Qué lograron los pingüinos de 2006? ¿Y qué no?","a":"Abrieron un debate nacional sobre la educación de mercado heredada de la LOCE y lograron que la ley fuera reemplazada por la LGE en 2009. Pero el acuerdo de 2007 se hizo sin ellos: su participación directa quedó a medias."},
    {"q":"¿Qué reclamaba el movimiento chileno de 2011?","a":"Educación pública, gratuita y de calidad, y más participación estudiantil en las reformas. Se organizó desde la Confech (primera marcha nacional el 28/4/2011). Se destacaron formas creativas: 1.800 horas de trote alrededor de La Moneda, el flashmob «Thriller» y el paro con la CUT (24–25/8)."},
    {"q":"¿Qué logró el movimiento colombiano de 2011?","a":"La MANE consiguió que el gobierno retirara el proyecto de reforma de la Ley 30 (anuncio el 9/11, retiro formal el 16/11/2011), que incluía la posibilidad de instituciones con ánimo de lucro. No logró en cambio que la nueva reforma se construyera de manera concertada."},
    {"q":"¿Qué pasó en Brasil en 2015–2016?","a":"En 2015, estudiantes secundarios ocuparon unas 200 escuelas en São Paulo contra la «reorganización escolar» (cierre de unas 90 escuelas) y consiguieron que el gobierno la suspendiera el 4 de diciembre. En 2016 las ocupaciones se extendieron a otros estados, sobre todo Paraná, contra la MP 746 y la PEC 241."},
    {"q":"¿Qué tienen en común Uruguay 1968, La Plata 1975 y Chile 2006 y 2019?","a":"El boleto: los estudiantes reclamaban transporte accesible. Es un ejemplo de cómo un reclamo cotidiano se vuelve un reclamo por derechos (y, en algunos casos, termina en represión)."},
    {"q":"¿Cómo participaron las mujeres?","a":"Estuvieron desde siempre (cuatro de los diez estudiantes de la Noche de los Lápices eran mujeres) pero el movimiento las hizo visibles con Camila Vallejo (Chile 2011), Ni Una Menos (3/6/2015), las ocupaciones brasileñas y el Mayo feminista chileno de 2018, que reclamó educación no sexista y protocolos contra el acoso."},
    {"q":"¿Los movimientos estudiantiles siempre lograron lo que buscaban?","a":"No. Algunos lograron cambios concretos (Córdoba 1918, Colombia 2011, São Paulo 2015), otros abrieron debates y otros fueron reprimidos sin conseguir sus objetivos inmediatos. Por eso conviene distinguir entre lo que buscaban y lo que consiguieron."},
    {"q":"¿Qué papel tuvo la represión?","a":"Fue un elemento constante en el siglo XX: Colombia 1929 y 1954, Argentina 1966 y 1976, Brasil y Uruguay 1968, México 1968 y 1971, El Salvador 1975. A veces frenó a los movimientos, pero también los volvió símbolos de memoria (8/6 en Colombia, 14/8 en Uruguay, 16/9 en Argentina, 2/10 en México)."},
    {"q":"¿Qué diferencia hay entre el movimiento secundario y el universitario?","a":"Los secundarios suelen reclamar por condiciones cotidianas (boleto, comida, edificios) y son menores de edad, por lo que la represión pesa distinto; los universitarios suelen tener federaciones con más historia y reclaman por gobierno universitario, aranceles y financiamiento."},
    {"q":"¿Por qué Ayotzinapa es un caso estudiantil?","a":"Porque los 43 desaparecidos (26/9/2014, Iguala) eran estudiantes de la Escuela Normal Rural «Raúl Isidro Burgos», que forma maestros rurales para jóvenes de sectores humildes. Es un caso de derechos humanos que sigue abierto."},
    {"q":"¿Cómo se relacionaron estudiantes y trabajadores?","a":"En el Cordobazo (1969) marcharon juntos; en Colombia (10/11/2011) los docentes de Fecode se sumaron a la marcha estudiantil; en Chile la CUT convocó un paro nacional (24–25/8/2011); en Argentina (2024–2025) marcharon junto a la FUA el Frente Sindical y el CIN."},
    {"q":"¿Qué papel tuvo la cultura?","a":"Los movimientos crearon un lenguaje propio: consignas, marchas del silencio, carteles, canciones, flashmobs y formas lúdicas (1.800 horas, abrazos a las universidades). Ese repertorio ayudó a sumar apoyo y a que la protesta se recordara."},
    {"q":"¿Qué diferencia hay entre dictadura y gobierno de facto?","a":"«De facto» describe cómo se llega al poder (sin elecciones); «dictadura» describe cómo se gobierna. En Argentina se usa la expresión «dictadura cívico-militar (1976–1983)» y se habla de terrorismo de Estado."},
    {"q":"¿Por qué Córdoba en 1918?","a":"Porque su universidad tenía un régimen muy cerrado y conservador (con fuerte influencia de sectores católicos), mientras la sociedad cambiaba por la inmigración y la expansión de la clase media. La mecha fue la clausura del internado del Hospital de Clínicas."},
    {"q":"¿Qué es una toma y por qué se usa?","a":"Es la ocupación de un edificio educativo. Se usa cuando los estudiantes sienten que los canales formales no los escuchan. Tiene antecedentes en 1918, y se repitió en Chile (2006, 2018) y Brasil (2015–2016). Es un recurso extremo y discutido."},
    {"q":"¿Y hoy? (Argentina 2024–2025)","a":"Hubo tres Marchas Federales Universitarias (23/4/2024, 2/10/2024 y 17/9/2025), convocadas por la FUA, el Frente Sindical y el CIN, en defensa del financiamiento de la universidad pública. Por ser un tema actual y discutido, presenten los hechos sin tomar partido."},
    {"q":"¿Qué pasó con la memoria?","a":"Cada país tiene su fecha: 8 de junio (Colombia, Día del Estudiante Caído), 14 de agosto (Uruguay, Mártires Estudiantiles), 16 de septiembre (Argentina) y 2 de octubre (México, con marcha anual)."},
    {"q":"¿Qué no sabemos con certeza?","a":"Cuántas personas murieron en Tlatelolco, cuántos estudiantes murieron el 9/6/1954 en Bogotá y cuántas víctimas hubo el 30/7/1975 en El Salvador. Decir «las cifras se discuten» es una respuesta correcta y más sólida que inventar un número."}
  ]
};
